### ISSUE TITLE
Failed to run RootFSBuilder on QubesOS

### ISSUE THREAD

**Issue by Zophike1** [0xricksanchez/like-dbg#78]
**Describe the bug**
Building like-dbg throws the error "Failed to run RootFSBuilder"

**To Reproduce**
1. The version is like-dbg v0.0.1
2. Running ./start-kgdb.py with out any additional flags runs up to src.docker_runner:wait_for_container:109 

**Expected behavior**
To actually run RootFSBuilder and extract the RootFS to build like-dbg's docker images.

**Screenshots**

![like-dbg](https://user-images.githubusercontent.com/30738233/186949774-52ea9bf2-9c5d-4925-a300-5cab9c2e1e71.png)

**Desktop (please complete the following information):**
Fill me in on the specs of your environment:
1. Operating system: Qubes OS 4.1.1, with like-dbg being run inside a debian 11 Qube
2. Python version is 3.9.2
3. Docker version 20.10.17, build 100c701

**Additional context**
Important note is that i'm running ./start-kdbg.py in a non-ctf context! without any additional flags. Docker can pull and build images just fine but the issue occurs when I run the aforementioned script.

**Comment by 0xricksanchez** [comment]
I do not have the means to test and set up QubesOS on my end right now. 

* Step 0: `docker build -f .dockerfile_base -t "like_dbg_base" --build-arg USER=user .`
* Step 1: `docker build -f .dockerfile_rootfs -t "like_rootfs" --build-arg USER=user .`
* Step 2: `docker run --privileged --rm -it -v "$(pwd)/io":/io like_rootfs /bin/bash`
* Step 3: `./home/user/rootfs.sh -n "filesystem" -a x86_64 -d bullseye -u user`

**Note:** I left out the `-p [package list]` argument for the `root.sh` script for brevity reasons. One could add the list as defined in `config.ini`.

The shown steps above should lead up to the same error as in the screenshot. The root cause of the error is not yet clear to me, but it seems that the location (`/io/rootfs`), in which `debootstrap` attempts to install the rootfs has not enough permissions. I do not know QubesOS enough to blindly ship a fix and without a working test-bench I cannot fix this.

I happily take a PR that fixes things on QubesOS, which I can then test again Debian/Fedora/Arch to ensure nothing breaks on those ends.

**Comment by 0xricksanchez** [comment]
The testing for this has become a lot easier with the latest additions to the main branch!

You can now invoke `./start_kgdb.py --partial 4` to only run *stage 4*, which builds a root filesystem.
